### ISSUE TITLE
Page Completion required to be True

### ISSUE THREAD

**Issue by kmcmurphy** [gowithfloat/adapt-next-button#3]
Using the Adapt authoring tool, the "Require Page Completion" option is required to be set to true or you receive a Validation failed error message when trying to save the page.

**Comment by mediabounds** [comment]
Ah, right you are. I was able to confirm and will address and get a new release out today!

**Comment by mediabounds** [comment]
I've just released version 0.9.2 which should resolve this issue--let me know!
