### ISSUE TITLE
displayTitle (string): The title to display on the button not present

### ISSUE THREAD

**Issue by jonathanbzxc136623** [gowithfloat/adapt-next-button#5]
Using within Authoring tool, displayTitle seems to be missing so you get a button bar with no way of adding text onto it. Could you have a look at an update?

**Comment by mediabounds** [comment]
Within the authoring tool, the `displayTitle` is the component title. Setting the component title should set the text on the button. Hope that helps!

**Comment by jonathanbzxc136623** [comment]
Thanks for clearing that up for me so quickly - my misunderstanding.
